on:
  push:
    branches:
      - main

name: Deploy Function

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: Check
          runtime: go113
          credentials: ${{ secrets.GCP_SA }}
